fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        #- id: check-added-large-files
        - id: end-of-file-fixer
        - id: trailing-whitespace
    - repo: local
      hooks:
        - id: lint
          name: lint
          entry: make lint
          language: system
